apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZGFtMHZoejkx
  CLOUDINARY_KEY: NTUzNzM3MTY5NTQ3MzEz
  CLOUDINARY_SECRET: SnpQVDByTFd0cC1rckNaTVgweEpYLU43NUE0
  MAPBOX_TOKEN: cGsuZXlKMUlqb2lhbmx2ZEdocExXUmxkaUlzSW1FaU9pSmpiV2xtZFdGNGJqRXdNREYxTTJSelpUZzFjV001Y1hCakluMC5GVWNXV1dhN2FFTHo0Ym1nMmR3bGZn
  DB_URL: bW9uZ29kYitzcnY6Ly9qeW90aGlnb3JsZTIwMDNfZGJfdXNlcjo8ZGJfcGFzc3dvcmQ+QGNsdXN0ZXIxLnJuaHNkZG0ubW9uZ29kYi5uZXQvP2FwcE5hbWU9Q2x1c3RlcjE=
  SECRET: bXVzdGFmYQ==
